import SearchIcon from "@mui/icons-material/Search";
import Avatar from "@mui/material/Avatar";
import CssBaseline from "@mui/material/CssBaseline";
import List from "@mui/material/List";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Paper from "@mui/material/Paper";
import * as React from "react";

import { Divider, alpha } from "@mui/material";
import InputBase from "@mui/material/InputBase";
import Toolbar from "@mui/material/Toolbar";
import { styled } from "@mui/system";
import { useNavigate } from "react-router-dom";
const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "https://mui.com/static/images/avatar/1.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "https://mui.com/static/images/avatar/2.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "https://mui.com/static/images/avatar/3.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "https://mui.com/static/images/avatar/1.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "https://mui.com/static/images/avatar/3.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "https://mui.com/static/images/avatar/2.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "https://mui.com/static/images/avatar/1.jpg",
  },
  {
    id: 8,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "https://mui.com/static/images/avatar/3.jpg",
  },
  {
    id: 9,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "https://mui.com/static/images/avatar/1.jpg",
  },
];

export default function ChatSidebar() {
  return (
    <React.Fragment>
      <CssBaseline />
      <Paper square sx={{ pb: "50px", boxShadow: "none" }}>
        <Toolbar>
          <Search>
            <SearchIconWrapper>
              <SearchIcon color="disabled" />
            </SearchIconWrapper>
            <StyledInputBase
              placeholder="Search…"
              inputProps={{ "aria-label": "search" }}
            />
          </Search>
        </Toolbar>

        <List sx={{ mb: 2 }}>
          {messages.map((item, i) => (
            <ChatItem item={item} key={i} />
          ))}
        </List>
      </Paper>
    </React.Fragment>
  );
}
interface Props {
  item: {
    id: number;
    person: string;
    secondary: string;
    primary: string;
  };
}
function ChatItem({ item }: Props) {
  // navigation routing
  const navigate = useNavigate();
  function onClick() {
    navigate(`/discus/123`);
  }

  const { id, person, primary, secondary } = item;
  return (
    <React.Fragment>
      {id === 1 && ( // < 5
        <ListSubheader sx={{ bgcolor: "background.paper" }}>
          Today
        </ListSubheader>
      )}
      {id === 5 && ( //   > 5
        <ListSubheader sx={{ bgcolor: "background.paper" }}>
          Yesterday
        </ListSubheader>
      )}
      <ListItemButton onClick={onClick}>
        <ListItemAvatar>
          <Avatar alt="Profile Picture" src={person} />
        </ListItemAvatar>
        <ListItemText primary={primary} secondary={secondary.slice(0, 30)} />
      </ListItemButton>

      <Divider variant="inset" component="li" />
    </React.Fragment>
  );
}

const Search = styled("div")(({ theme }) => ({
  position: "relative",
  borderRadius: theme.shape.borderRadius,
  backgroundColor: alpha(theme.palette.common.black, 0.15),
  "&:hover": {
    backgroundColor: alpha(theme.palette.common.black, 0.25),
  },
  marginLeft: 0,
  width: "100%",
}));

const SearchIconWrapper = styled("div")(({ theme }) => ({
  padding: theme.spacing(0, 2),
  height: "100%",
  position: "absolute",
  pointerEvents: "none",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
}));

const StyledInputBase = styled(InputBase)(({ theme }) => ({
  color: "inherit",
  width: "100%",
  "& .MuiInputBase-input": {
    padding: theme.spacing(1, 1, 1, 0),
    // vertical padding + font size from searchIcon
    paddingLeft: `calc(1em + ${theme.spacing(4)})`,
  },
}));
